### ISSUE TITLE
Error when get int value insted of double

### ISSUE THREAD

**Issue by EliteX23** [progaudi/tarantool-csharp#92]
Hi. I have a problem.
There is space with two columns. The first one  is name (index), the second one is marks (isn’t index). I'm trying to get all data from space :
`var data = await primaryIndex.Select<TarantoolTuple<string>,
                    TarantoolTuple<string,double>>(
                    TarantoolTuple.Create(String.Empty), new SelectOptions
                    {
                        Iterator = Iterator.All
                    });`
If mark in space is double e.g. 25.5 it's OK but if it's 25 - integer I get exception "Expected double, got integer". Using long instead of double in my code doesn't help I've got error for double e.g. 25.

**Comment by aensidhe** [comment]
Hi.

Unfortunately, this is known issue. Tarantool stored your 25 as integer and our float parser fails to decode it. We will think how to address it.

Thank you for feedback.

**Comment by aensidhe** [comment]
@EliteX23 try to use version 0.7.0

**Comment by EliteX23** [comment]
Great, it works. thnx
